name: CI

on:
  push:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        submodules: 'recursive'
    - uses: arduino/setup-arduino-cli@v1.1.1
    - name: Install platform and compile
      run: |
        arduino-cli core update-index
        arduino-cli core install arduino:avr
        cd ./hsldz_totp_lock && arduino-cli compile --fqbn arduino:avr:uno --libraries ../vendor/librares/
