name: CI

on:
  push:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: arduino/setup-arduino-cli@v1.1.1
    - name: Install platform and compile
      run: |
        cp Secrets.h.example Secrets.h
        arduino-cli core update-index
        arduino-cli core install arduino:avr
        arduino-cli compile --fqbn arduino:avr:uno --libraries vendor/librares/ hslock.ino
